
LOGGING:
  #LOGMODE: FILE
  LOGMODE: CONSOLE
  LOGFILE: sml2mqtt.log
  LOGSERVER: 192.168.2.20
  LOGLEVEL: INFO

BROKER:
  BROKER: 192.168.2.20
  PORT: 1883
  PUBLISH: SMARTHOME/DE/IN/SML01/STATUS
  LWT_TOPIC: SMARTHOME/DE/IN/SML01/STATUS/STATE

SML:
  SERIAL: /dev/ttyUSB0
  BAUDRATE: 9600
  UPDATE_INTERVAL: 15
  STARTUP_DELAY: 5
